"""Add additional information about the beer, plus a cached search string to query against

Revision ID: 1dc2f4c6ba3a
Revises: a5f2eb1ed93
Create Date: 2015-06-07 16:29:06.572154

"""

# revision identifiers, used by Alembic.
revision = "1dc2f4c6ba3a"
down_revision = "a5f2eb1ed93"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("beers", sa.Column("brew_with", sa.Text(), nullable=True))
    op.add_column("beers", sa.Column("brew_year", sa.Integer(), nullable=True))
    op.add_column("beers", sa.Column("search_string", sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("beers", "search_string")
    op.drop_column("beers", "brew_year")
    op.drop_column("beers", "brew_with")
    ### end Alembic commands ###
