"""empty message

Revision ID: a5f2eb1ed93
Revises: 57c55bb3959f
Create Date: 2015-04-19 15:46:59.798707

"""

# revision identifiers, used by Alembic.
revision = 'a5f2eb1ed93'
down_revision = '57c55bb3959f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beers', sa.Column('country_iso', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beers', 'country_iso')
    ### end Alembic commands ###
